export const MANAGE_PLATFORM_CONFIGURATION_PERMISSION = "PERM-MANAGE-PLATFORM-CONFIGURATION";

export const SETTING_VALUE_TYPES = [
  "STRING",
  "NUMBER",
  "BOOLEAN",
  "JSON",
  "SECRET_REFERENCE",
] as const;

export const CONFIG_REVISION_STATUSES = ["DRAFT", "ACTIVE", "ARCHIVED"] as const;

export const TRANSLATION_STATUSES = ["DRAFT", "PUBLISHED", "ARCHIVED"] as const;

export const PLATFORM_CONFIGURATION_EVENT = {
  pdfTemplateRevised: "PLATFORM_PDF_TEMPLATE_REVISED",
  settingCreated: "PLATFORM_SETTING_CREATED",
  settingRevised: "PLATFORM_SETTING_REVISED",
  snapshotViewed: "PLATFORM_CONFIGURATION_VIEWED",
  translationsPublished: "PLATFORM_TRANSLATIONS_PUBLISHED",
  notificationTemplateRevised: "PLATFORM_NOTIFICATION_TEMPLATE_REVISED",
  workflowTemplateRevised: "PLATFORM_WORKFLOW_TEMPLATE_REVISED",
} as const;
