export const MANAGE_ONE_TIME_SERVICES_PERMISSION = "PERM-MANAGE-ONE-TIME-SERVICES";

export const ONE_TIME_SERVICE_PATHS = ["Build", "Digital"] as const;

export const ONE_TIME_CATALOG_EVENT = {
  categoryCreated: "CATALOG_ONE_TIME_CATEGORY_CREATED",
  categoryUpdated: "CATALOG_ONE_TIME_CATEGORY_UPDATED",
  categoryStatusChanged: "CATALOG_ONE_TIME_CATEGORY_STATUS_CHANGED",
  categoryReordered: "CATALOG_ONE_TIME_CATEGORY_REORDERED",
  serviceCreated: "CATALOG_ONE_TIME_SERVICE_CREATED",
  serviceUpdated: "CATALOG_ONE_TIME_SERVICE_UPDATED",
  serviceStatusChanged: "CATALOG_ONE_TIME_SERVICE_STATUS_CHANGED",
  serviceReordered: "CATALOG_ONE_TIME_SERVICE_REORDERED",
  pricingChanged: "CATALOG_ONE_TIME_PRICING_CHANGED",
  durationChanged: "CATALOG_ONE_TIME_DURATION_CHANGED",
  phasesChanged: "CATALOG_ONE_TIME_PHASES_CHANGED",
  deliverablesChanged: "CATALOG_ONE_TIME_DELIVERABLES_CHANGED",
  tasksChanged: "CATALOG_ONE_TIME_TASKS_CHANGED",
} as const;
