export const MANAGE_REQUEST_TEMPLATES_PERMISSION = "PERM-MANAGE-REQUEST-TEMPLATES";

export const REQUEST_TEMPLATE_FIELD_TYPES = [
  "SHORT_TEXT",
  "LONG_TEXT",
  "NUMBER",
  "DATE",
  "DROPDOWN",
  "MULTI_SELECT",
  "CHECKBOX",
  "RADIO",
  "FILE",
  "EMAIL",
  "PHONE",
  "AMOUNT",
  "URL",
] as const;

export const REQUEST_TEMPLATE_REVISION_STATUSES = [
  "SUGGESTED",
  "DRAFT",
  "ACTIVE",
  "ARCHIVED",
] as const;

export const REQUEST_FORM_COMPLETENESS_STATUSES = [
  "COMPLETE",
  "MISSING_REQUIRED_FIELDS",
  "MISSING_REQUIRED_ATTACHMENTS",
  "PENDING_INTERNAL_REVIEW",
] as const;

export const REQUEST_TEMPLATE_EVENT = {
  snapshotViewed: "REQUEST_TEMPLATE_SNAPSHOT_VIEWED",
  suggestedApplied: "REQUEST_TEMPLATE_SUGGESTED_APPLIED",
  templateRevised: "REQUEST_TEMPLATE_REVISED",
  versionStatusChanged: "REQUEST_TEMPLATE_VERSION_STATUS_CHANGED",
  fieldLibraryCreated: "REQUEST_FIELD_LIBRARY_CREATED",
  fieldLibraryUpdated: "REQUEST_FIELD_LIBRARY_UPDATED",
  activeTemplateViewed: "REQUEST_TEMPLATE_ACTIVE_VIEWED",
  formResponseSubmitted: "REQUEST_TEMPLATE_FORM_RESPONSE_SUBMITTED",
} as const;
