export const MANAGE_MONTHLY_SERVICES_PERMISSION = "PERM-MANAGE-MONTHLY-SERVICES";
export const MANAGE_SERVICE_ITEMS_PERMISSION = "PERM-MANAGE-SERVICE-ITEMS";
export const MANAGE_SERVICE_LEVELS_PERMISSION = "PERM-CONFIGURE-GROWTH-ADVANCED-PARTNERSHIP-LEVELS";

export const CATALOG_CODE_PATTERN = /^[A-Z0-9]+(?:-[A-Z0-9]+)*$/;

export const MONTHLY_SERVICE_COMPATIBILITY_CATEGORY = {
  code: "JZOOM-INTERNAL-MONTHLY",
  nameAr: "خدمات شهرية",
  nameEn: "Monthly services",
} as const;

export const CATALOG_EVENT = {
  serviceCreated: "CATALOG_MONTHLY_SERVICE_CREATED",
  serviceUpdated: "CATALOG_MONTHLY_SERVICE_UPDATED",
  serviceStatusChanged: "CATALOG_MONTHLY_SERVICE_STATUS_CHANGED",
  serviceReordered: "CATALOG_MONTHLY_SERVICE_REORDERED",
  serviceHoursChanged: "CATALOG_MONTHLY_SERVICE_HOURS_CHANGED",
  serviceRatesChanged: "CATALOG_MONTHLY_SERVICE_RATES_CHANGED",
  itemCreated: "CATALOG_SERVICE_ITEM_CREATED",
  itemUpdated: "CATALOG_SERVICE_ITEM_UPDATED",
  itemStatusChanged: "CATALOG_SERVICE_ITEM_STATUS_CHANGED",
  itemReordered: "CATALOG_SERVICE_ITEM_REORDERED",
  itemLevelsChanged: "CATALOG_SERVICE_ITEM_LEVELS_CHANGED",
  levelCreated: "CATALOG_SERVICE_LEVEL_CREATED",
  levelUpdated: "CATALOG_SERVICE_LEVEL_UPDATED",
  levelStatusChanged: "CATALOG_SERVICE_LEVEL_STATUS_CHANGED",
  levelReordered: "CATALOG_SERVICE_LEVEL_REORDERED",
} as const;
